<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AddPost</title>
    <link rel = "stylesheet" href = "../reset.css">
    <link rel = "stylesheet" href = "../style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Marko+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Anta&family=Marko+One&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Anta&family=IM+Fell+English+SC&family=Marko+One&family=Staatliches&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Anta&family=IM+Fell+English+SC&family=Marko+One&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Staatliches&display=swap" rel="stylesheet">

</head>
<body>
    <header>
        <hgroup>
            <nav class = "navbar">
                <a id ="first-header-element" href = "../index.php">Home<span>.</span></a>
                <div class = "hamburger" >&#9776;</div>

                <ul>
                    <?php
                        ini_set('display_errors', 1);
                        //error_reporting(E_ALL);
                        //mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
                        session_start();
                        
                        $logout_link = '
                        <li><a id = "last-header-element" href = "logout.php">Logout</a></li>
                        ';

                        $addPost_link = '
                        <li><a href = "addPost.php">Add Post</a></li>
                        ';

                        $login_link = '
                        <li><a id = "last-header-element" href = "../login.html">Login</a></li>
                        ';

                        if ((isset($_SESSION['loggedin']) && $_SESSION['loggedin'])) {//if loggedin -logout, addpost
                            if((isset($_SESSION['admin']) && $_SESSION['admin'])) {
                                echo $addPost_link;
                                echo $logout_link;
                                
                            }
                            else{
                                echo $logout_link;
                            }
                            
                            

                        } 
                        else{//if not loggeed in - login 
                            echo $login_link;

                        }
                    ?>
                    
                    
                    
                </ul>
            </nav>
        </hgroup>
    </header>
    
    <article class = "viewBlog">
        
        <?php

            // Define a custom sort function
            function sortPostsByTimestamp($a, $b, $field) {
                return strtotime($b[$field]) - strtotime($a[$field]);
            }

            //bubble sort generated by gen ai 

            function bubbleSortPosts(&$posts, $field) {
                $n = count($posts);
                do {
                    $swapped = false;
                    for ($i = 0; $i < $n - 1; $i++) {
                        // Use the sortPostsByTimestamp function to decide order
                        if (sortPostsByTimestamp($posts[$i], $posts[$i + 1], $field) > 0) {
                            // Swap the posts if they are in the wrong order
                            $temp = $posts[$i];
                            $posts[$i] = $posts[$i + 1];
                            $posts[$i + 1] = $temp;
                            $swapped = true;
                        }
                    }
                    $n--; // Reduce the array size for optimization
                } while ($swapped);
            }
            // end of bubble sort
            $selectedMonth = isset($_GET['months']) ? $_GET['months'] : 'all';

            $dropdown = '
            <form id = "months-form" method="get" action="">
            <div class = "dropdown">
            <h1>View posts by: <span> </span></h1>
            <select id="months" name="months">
                <option value="all"' . ($selectedMonth == 'all' ? ' selected' : '') . '>All time</option>
                <option value="january"' . ($selectedMonth == 'january' ? ' selected' : '') . '>January</option>
                <option value="february"' . ($selectedMonth == 'february' ? ' selected' : '') . '>February</option>
                <option value="march"' . ($selectedMonth == 'march' ? ' selected' : '') . '>March</option>
                <option value="april"' . ($selectedMonth == 'april' ? ' selected' : '') . '>April</option>
                <option value="may"' . ($selectedMonth == 'may' ? ' selected' : '') . '>May</option>
                <option value="june"' . ($selectedMonth == 'june' ? ' selected' : '') . '>June</option>
                <option value="july"' . ($selectedMonth == 'july' ? ' selected' : '') . '>July</option>
                <option value="august"' . ($selectedMonth == 'august' ? ' selected' : '') . '>August</option>
                <option value="september"' . ($selectedMonth == 'september' ? ' selected' : '') . '>September</option>
                <option value="october"' . ($selectedMonth == 'october' ? ' selected' : '') . '>October</option>
                <option value="november"' . ($selectedMonth == 'november' ? ' selected' : '') . '>November</option>
                <option value="december"' . ($selectedMonth == 'december' ? ' selected' : '') . '>December</option>
            </select>
            </div>
            </form>';
            
            $no_posts_month = '<p id = "np-month">No posts this month</p>';
            $no_posts = '<p id = "no-posts" >Posts are coming soon!</p>';
            
            
            define('DB_HOST', 'localhost');
            define('DB_USER', 'root');
            define('DB_PASSWORD', '12345');
            define('DB_NAME', 'users');

            $conn = new mysqli(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);

            if($conn->connect_error){
                die("Connection failed: " . $conn->connect_error);
            }
            $sql = "Select title, description, user_email, post_time, id FROM entries";

            $result = $conn->query($sql);
            if($result ->num_rows>0){
                
                $posts = array();
                while ($row = $result->fetch_assoc()) {
                    if ($selectedMonth == 'all' || strtolower(date("F", strtotime($row['post_time']))) == $selectedMonth) {
                        $posts[] = $row;
                        
                    }
                }
                

                echo $dropdown;
                if (count($posts)==0){
                    echo $no_posts_month;
                }
                

                

                // Sort the posts array using bubble sort and the custom sort function
                bubbleSortPosts($posts, 'post_time');

                // Iterate over the sorted array to display the blog posts
                echo '<div class="blog-box">';
                
                if((isset($_SESSION['admin']) && $_SESSION['admin'])) {
                    $deleteBut = 1;
                }
                else{
                    $deleteBut = 0;
                }
                
                foreach ($posts as $post) {
                    $sql = "Select name FROM users WHERE email = '" . $post['user_email'] . "'";

                    $result = $conn->query($sql);
                    
                    if($result->num_rows>0){
                        $row = $result->fetch_assoc();
                        $author = $row['name'];
                    }
                    $formattedDate = date("d.m.Y H:i:s", strtotime($post['post_time'])); // Formatting the timestamp to a date
                    

                    $blog_post_start = 
                    '
                    <div class="blog-post" id="'. $post['id'] .'">
                                <i class="delete fas fa-trash-alt"></i>
                                <div class="blog-text">                                   
                                    <h3>' . htmlspecialchars($post['title']) . '</h3>
                                    
                                
                                    <p>' . htmlspecialchars($post['description']) . '</p>
                                    <hr>
                                    <div class="blog-date-author">
                                        <p>' . $formattedDate . '</p>
                                        <p>' . $author . '</p>
                                    </div>
                                    <hr>
                    ';


                    $blog_post_end = 
                        '
                                </div>
                            </div>
                        ';
                    
                    $blog_post_noadmin_start = 
                    '
                    <div class="blog-post">
                            <div class="blog-text">                                   
                                <h3>' . htmlspecialchars($post['title']) . '</h3>
                                
                            
                                <p>' . htmlspecialchars($post['description']) . '</p>
                                <hr>
                                <div class="blog-date-author">
                                    <p>' . $formattedDate . '</p>
                                    <p>' . $author . '</p>
                                </div>
                                <hr>
                    ';


                    if($deleteBut == 1){
                        echo $blog_post_start;
                    }
                    else{
                        echo $blog_post_noadmin_start;
                    }

                    

                    

                    $sql2 = "Select author_id, comment_text, comment_time, comment_id from comments where post_id = '" . $post['id'] . "'";
                    //select the author, the comment from comments where post_id = the id of the current post
                    $result2 = $conn->query($sql2);

                    if($result ->num_rows>0){//create an array of comments for the current post
                        $comments = array();
                        while($row = $result2->fetch_assoc()){
                            $comments[] = $row;
                        }
                    }

                    bubbleSortPosts($comments, 'comment_time');//use the same algorithm to sort it like posts

                    if((isset($_SESSION['name']) && isset($_SESSION['id']))){
                        $author_name = $_SESSION['name'];
                        $id = $_SESSION['id'];
                    }else{
                        $author_name = '';
                        $id = '';
                    }

                    $comment_loggedin_start = //allow to post comments
                    '
                    <div class = "comments">
                        <div class = "comments-heading">
                            <p>Comments</p>
                            <i  class="fa-solid fa-comment expand-comments-section"></i>  
                        </div>
                        <div class = "comment-content">
                            <div class = "add-comment">
                                <p>Comment what you think, ' .$author_name .' :</p>
                                <form action = "addComment.php" method = "POST" class = "comment-form">
                                    <input class = "add-comment" type = "text" name = "commentText">
                                    <input class = "add-comment-submit" type = "submit" value = "Submit">
                                    <input type="hidden" name="postId" value="' . htmlspecialchars($post['id']) . '">
                                    <input type="hidden" name="authorId" value="' . $id . '">
                        
                                </form>
                            </div>';
        
                    $comment_loggedin_end='
                        </div>
                    </div>
                    ';


                    

                    $comment_loggedout_start = //dont allow to post comments
                    '
                    <div class = "comments">
                        <div class = "comments-heading">
                            <p>Comments</p>
                            <i  class="fa-solid fa-comment expand-comments-section"></i>  
                        </div>
                        <div class = "comment-content">
                            
                            
                    
                    ';

                    $comment_loggedout_end = 
                    '
                        </div>
                    </div>
                    ';

                    $comment_box_start = //without delete button
                    '
                    <div class = "actual-comment">
                        <div class = "actual-comment-text">
                        
                    
                    ';

                    $comment_box_end_admin = //with delete button
                    '
                    <i class="delete-comment fas fa-trash-alt" data-comment-id="<?php echo htmlspecialchars($comment["id"]); ?></i>
                    </div>
                    </div>
                    ';

                    $comment_box_end = 
                    '
                    </div>
                    </div>
                    ';


                    
                    if ((isset($_SESSION['loggedin']) && $_SESSION['loggedin'])) {//if logged in
                        echo $comment_loggedin_start;
                        
                        foreach( $comments as $comment){
                            echo $comment_box_start;//the actual comment
                            $sql3 = "Select name from users where id = '" . $comment['author_id'] . "'";
                            //select the name from the user where the id matches the author_id
                            $result3 = $conn->query($sql3);
                            //fetch the result from this query 
                            if($result3->num_rows> 0){
                                $row = $result3->fetch_assoc();
                                $name = $row['name'];//fetch the name 
                            }
                            echo '<p class="comment-text" id=' . $comment['comment_id'] . '>' . htmlspecialchars($name) . ': ' . htmlspecialchars($comment['comment_text']) . '</p>';
                            //put this name in the according format along with the comment text
                            if((isset($_SESSION['admin'])) && $_SESSION['admin']){//if admin - delete button
                                //end the comment with delete button
                                echo $comment_box_end_admin;
    
                            }else{
                                echo $comment_box_end;
                                //end the comment without delete button
                            }
                            
                        };
                        
                        
                        
                        echo $comment_loggedin_end;
                    }
                    else{
                        echo $comment_loggedout_start;
                        
                        foreach( $comments as $comment){
                            echo $comment_box_start;
                            $sql3 = "Select name from users where id = '" . $comment['author_id'] . "'";
                            //select the name from the user where the id matches the author_id
                            $result3 = $conn->query($sql3);
                            //fetch the result from this query 
                            if($result3->num_rows> 0){
                                $name = $result3->fetch_assoc()['name'];//fetch the name 
                            }
                            echo '<p>' . htmlspecialchars($name) . ': ' . htmlspecialchars($comment['comment_text']) . '</p>';
                            //put this name in the according format along with the comment text
                            echo $comment_box_end;
                        };
                        echo $comment_loggedout_end;
                    }
                    echo $blog_post_end;
                    
                }
                echo'</div>';
            }else{
                echo $no_posts;
            }
            
            
        ?>
        
    </article>

    <footer id = "post-footer">
        <p>© 2024 Ekaterina Radaeva</p>
    </footer>
</body>
<script src = "../function.js"></script>
</html>